title: Entropista
email: asa.art@riseup.net
description: "Cultura Digital, Cibercultura, Comunicação e publicações diversas"

markdown: redcarpet
highlighter: pygments
permalink: /:title

url:
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
